export const pages = [
  {
    title: 'Home',
    path: '/',
    tabItem: true,
    drawerItem: true,
    activeIndex: 0,
    footerBox: 1,
  },
  {
    title: 'Services',
    path: '/services',
    tabItem: true,
    menuItem: true,
    attachMenu: true,
    drawerItem: true,
    activeIndex: 1,
    selectedIndex: 0,
    footerBox: 2,
  },
  {
    title: 'The Revolution',
    path: '/revolution',
    tabItem: true,
    drawerItem: true,
    activeIndex: 2,
    footerBox: 3,
  },
  {
    title: 'About Us',
    path: '/about',
    tabItem: true,
    drawerItem: true,
    activeIndex: 3,
    footerBox: 4,
  },
  {
    title: 'Contact Us',
    path: '/contact',
    tabItem: true,
    drawerItem: true,
    activeIndex: 4,
    footerBox: 5,
  },
  {
    title: 'Custom Software',
    path: '/cutomsoftware',
    menuItem: true,
    activeIndex: 1,
    selectedIndex: 1,
    footerBox: 2,
  },
  {
    title: 'Mobile Apps',
    path: '/mobileapps',
    menuItem: true,
    activeIndex: 1,
    selectedIndex: 2,
    footerBox: 2,
  },
  {
    title: 'Websites',
    path: '/websites',
    menuItem: true,
    activeIndex: 1,
    selectedIndex: 3,
    footerBox: 2,
  },
  { title: 'Free Estimate', path: '/estimate', drawerItem: true },
  { title: 'Vision', path: '/vision', footerBox: 3 },
  { title: 'Technology', path: '/technology', footerBox: 3 },
  { title: 'Process', path: '/process', footerBox: 3 },
  { title: 'Mission Statement', path: '/mission', footerBox: 4 },
  { title: 'History', path: '/history', footerBox: 4 },
  { title: 'Team', path: '/team', footerBox: 4 },
];
