export const pages = [
  { title: 'Home', path: '/', tabItem: true, drawerItem: true, activeIndex: 0 },
  {
    title: 'Services',
    path: '/services',
    tabItem: true,
    menuItem: true,
    attachMenu: true,
    drawerItem: true,
    activeIndex: 1,
    selectedIndex: 0,
  },
  {
    title: 'The Revolution',
    path: '/revolution',
    tabItem: true,
    drawerItem: true,
    activeIndex: 2,
  },
  {
    title: 'About Us',
    path: '/about',
    tabItem: true,
    drawerItem: true,
    activeIndex: 3,
  },
  {
    title: 'Contact Us',
    path: '/contact',
    tabItem: true,
    drawerItem: true,
    activeIndex: 4,
  },
  {
    title: 'Custom Software',
    path: '/cutomsoftware',
    menuItem: true,
    activeIndex: 1,
    selectedIndex: 1,
  },
  {
    title: 'Mobile Apps',
    path: '/mobileapps',
    menuItem: true,
    activeIndex: 1,
    selectedIndex: 2,
  },
  {
    title: 'Websites',
    path: '/websites',
    menuItem: true,
    activeIndex: 1,
    selectedIndex: 3,
  },
  { title: 'Free Estimate', path: '/estimate', drawerItem: true },
];
